"""All 105 splits keys, in original order from golden match-001.json."""

SPLITS_KEYS = [
    "Offside", "Pass with packing", "Pass packing value", "Pass into pen. area",
    "Key pass", "Cross", "Entries in box", "Assist", "Second assist", "Third assist",
    "Shot on target assist", "Sprint forward", "Progressive pass",
    "Progressive pass success", "Progressive pass accuracy", "Pass to final third",
    "Pass to final third success", "Pass to final third accuracy",
    "Pass", "Pass success", "Pass accuracy",
    "Pass forward", "Pass forward success", "Pass forward accuracy",
    "Pass back", "Pass back success", "Pass back accuracy",
    "Pass sideways", "Pass sideways success", "Pass sideways accuracy",
    "Pass short", "Pass short success", "Pass short accuracy",
    "Pass middle", "Pass middle success", "Pass middle accuracy",
    "Pass long", "Pass long success", "Pass long accuracy",
    "Touches in pen. area", "Received pass", "Fouls suffered",
    "Lose on own half", "Dangerous loses on own half", "Autogoal",
    "Technical mistake", "Lost ball", "Dribble", "Dribble success",
    "Success rate", "Dribble packing", "Dribble packing value",
    "Goal actions", "Goal", "Shot", "Shot success", "Shot accuracy",
    "Shot by head", "Shot by head success", "Shot by head accuracy",
    "Free kick shot", "Free kick shot success", "Free kick shot accuracy",
    "Free kick pass", "Free kick pass success", "Free kick pass accuracy",
    "Direct free kick", "Success", "Accuracy",
    "Free kick with shot", "Penalty", "Penalty success",
    "Throwing", "Throwing success", "Throwing accuracy",
    "Tackle", "Tackle success", "Sliding tackles",
    "Dribble against", "Return", "Return on opp. half",
    "Tackle & recovery", "Tackle & recovery on opp. half",
    "Blocked shot", "Clearance", "Clearance success",
    "Foul", "Interception", "Sprint back", "Recovery",
    "Yellow card", "Red card",
    "Duel", "Duel success", "Ariel duel", "Ariel duel success",
    "Pressing", "Contrpressing",
    "Save", "Shots against", "Goalkeeper exits",
    "Goal kick", "Goal kick success", "Short goal kicks", "Long goal kicks",
]
